gitea-setup job code fixed

diff --git a/util/gitea/4.gitea-setup-job.yaml b/util/gitea/4.gitea-setup-job.yaml
--- a/util/gitea/4.gitea-setup-job.yaml
+++ b/util/gitea/4.gitea-setup-job.yaml
@@ -27,7 +27,8 @@ spec:
         args:
         - |-
           echo "------------------------------"
-          curl -f -LI http://${GITEA_HOST}/
+          echo " Checking http://${GITEA_HOST}/"
+          curl -sf -LI http://${GITEA_HOST}/
           RET=$?
           if [ ${RET} -ne 0 ]; then
             echo "ERROR curl to GITEA_HOST=${GITEA_HOST} failed with ${RET}"
@@ -39,6 +40,12 @@ spec:
           TOKEN_NAME="install-$RANDOM"
           GITEA_INSTALL_TOKEN=$(curl -s -XPOST -H "Content-Type: application/json"  -k -d '{"name":"'"${TOKEN_NAME}"'"}' -u opentlc-mgr:r3dh4t1\! http://${GITEA_HOST}/api/v1/users/opentlc-mgr/tokens | jq -r .sha1)
           echo "GITEA_INSTALL_TOKEN=${GITEA_INSTALL_TOKEN}"
+          if [ -z "${GITEA_INSTALL_TOKEN}" ]; then
+            echo "ERROR no GITEA_INSTALL_TOKEN was returned, exiting"
+            sleep ${SLEEP_TIME}
+            echo "------------------------------"
+            exit ${RET}
+          fi
 
           for i in $(seq 1 $COUNT); 
           do
