debug info added

diff --git a/apps/cicd/templates/01-cluster-tasks/yq-eval-inplace-cluster-task.yaml b/apps/cicd/templates/01-cluster-tasks/yq-eval-inplace-cluster-task.yaml
--- a/apps/cicd/templates/01-cluster-tasks/yq-eval-inplace-cluster-task.yaml
+++ b/apps/cicd/templates/01-cluster-tasks/yq-eval-inplace-cluster-task.yaml
@@ -38,10 +38,27 @@ spec:
       script: >
         #!/bin/sh
 
+        echo "SELECT_EXPRESSION=$(params.SELECT_EXPRESSION)"
+        echo "NEW_VALUE=$(params.NEW_VALUE)"
+        echo "FILE_TO_UPDATE=$(params.FILE_TO_UPDATE)"
+
+        if [ ! -f $(params.FILE_TO_UPDATE) ]; then
+          echo "======== ERROR "========"
+          echo "File not found, aborting"
+          ls -ltrh
+          exit 1;
+        fi;
+
+        echo "======== BEFORE CHANGES "========"
+        cat $(params.FILE_TO_UPDATE)
+
         # Update target with new value
         #yq -i eval '(.images.[] | select(.name == "gramola-events*")).newTag |= "111111"' ./events-deployment/overlays/dev/kustomization.yml
         yq -i eval '$(params.SELECT_EXPRESSION) |= "$(params.NEW_VALUE)"' $(params.FILE_TO_UPDATE)
         
+        echo "======== AFTER CHANGES "========"
+        cat $(params.FILE_TO_UPDATE)
+
         #echo -n "true" > $(results.SUCCESS)
   workspaces:
     - mountPath: /workspace/source
